update
update

update

Add threadx (#2)

* Add threadx

* Add missing files

Co-authored-by: Antonio cuadros <acuadros1995@gmail.com>
Removed submodule e2studio_project/micro_ros_renesas2estudio_component

Add submodules


update submodules

update cmake

fix

fix

fix

fix

fix

update

Modify micro-ROS library build method

entity creation test

entity creation test

update

Create test base class to add parameters (#3)

* Modify test class to add parameters

* Move aux class definition

* Update freq test with config file

* Fix remove function

Co-authored-by: Pablo Garrido <pablogs9@gmail.com>
update

update

update

time sync test

time sync test

Use same test file for bot projects (#4)


time sync test

update

update

Set relative paths on project build (#5)


update

updates

add service client test

Add domain ID and Ping (#6)

* Add domain ID test

* Rename test files
update

update

update

update

update

update

Add FreeRTOS project (#7)

* Add FreeRTOS project

* Update UDP transport

* Update with foxy

* Add continuos fragment test

* Add utils to freeRTOS

* Add TODO

* Solve conflicts

Co-authored-by: Pablo Garrido <pablogs9@gmail.com>
update

update

update

update

update

update

update

update

update

update

updates

updates

updates

Add destruction test and auto test build (#8)


updates

updates

update

update

update

Remove map


Remove files

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,11 +10,11 @@ on:
 
 jobs:
   micro_ros_renesas_testbench:
-    runs-on: self-hosted
     strategy:
       fail-fast: false
       matrix:
-        ros_distribution: [ foxy ]
+        ros_distribution: [ foxy, galactic ]
+    runs-on: rpi-ros2-${{ matrix.ros_distribution }}
     steps:
     # - uses: ros-tooling/setup-ros@0.2.1
     #   with:
@@ -26,22 +26,55 @@ jobs:
       with:
         path: ros_ws/src/micro_ros_renesas_testbench
         submodules: recursive
+        ref: ${{ matrix.ros_distribution }}
         token: ${{ secrets.PRIVATE_KEY }}
-    - name: Install toolchain
-      run: |
-        cd ros_ws/src/micro_ros_renesas_testbench
-        ./installtoolchain.sh
     - name: Download dependencies
       run: |
         cd ros_ws
         vcs import --input src/micro_ros_renesas_testbench/requirements.repos src
     - name: Build micro-ROS library
       run: |
-        cd ros_ws/src/micro_ros_renesas_testbench/e2studio_project/micro-ROS_tests
-        mv makefile.init makefile.init.old
-        make clean && make -j$(nproc)
-    - name: Build tests
+        pushd ros_ws/src/micro_ros_renesas_testbench/e2studio_project/micro_ros_renesas2estudio_component
+          rm -rf libmicroros
+        popd
+        pushd ros_ws/src/micro_ros_renesas_testbench/e2studio_project/micro-ROS_tests
+          mv makefile.init makefile.init.old || true
+          make clean && make -j$(nproc)
+        popd
+
+        pushd ros_ws/src/micro_ros_renesas_testbench/e2studio_project_freeRTOS/micro_ros_renesas2estudio_component
+          rm -rf libmicroros
+        popd
+
+        # Copying library to speed up tests
+        cp -r ros_ws/src/micro_ros_renesas_testbench/e2studio_project/micro_ros_renesas2estudio_component/libmicroros/ ros_ws/src/micro_ros_renesas_testbench/e2studio_project_freeRTOS/micro_ros_renesas2estudio_component/
+
+        pushd ros_ws/src/micro_ros_renesas_testbench/e2studio_project_freeRTOS/micro-ROS_tests
+          mv makefile.init makefile.init.old || true
+          make clean && make -j$(nproc)
+        popd
+
+        pushd ros_ws/src/micro_ros_renesas_testbench/e2studio_project_threadX/micro_ros_renesas2estudio_component
+          rm -rf libmicroros
+        popd
+
+        # Copying library to speed up tests
+        cp -r ros_ws/src/micro_ros_renesas_testbench/e2studio_project/micro_ros_renesas2estudio_component/libmicroros/ ros_ws/src/micro_ros_renesas_testbench/e2studio_project_threadX/micro_ros_renesas2estudio_component/
+
+        pushd ros_ws/src/micro_ros_renesas_testbench/e2studio_project_threadX/micro-ROS_tests
+          mv makefile.init makefile.init.old || true
+          make clean && make -j$(nproc)
+        popd
+    - name: Build micro-ROS agent
       run: |
         source /opt/ros/${{ matrix.ros_distribution }}/setup.sh
         cd ros_ws
-        colcon build --cmake-clean-cache --cmake-force-configure
+        colcon build --cmake-clean-cache --cmake-force-configure --packages-up-to micro_ros_agent
+    - name: Build and run tests
+      run: |
+        source /opt/ros/${{ matrix.ros_distribution }}/setup.sh
+        cd ros_ws
+        source install/local_setup.bash
+        colcon build --cmake-clean-cache --cmake-force-configure --packages-up-to micro_ros_renesas_testbench
+        # colcon test --event-handlers console_direct+ --packages-select=micro_ros_renesas_testbench --return-code-on-test-failure --ctest-args -E "(cpplint)|(lint_cmake)|(uncrustify)|(xmllint)"
+        ./build/micro_ros_renesas_testbench/micro_ros_renesas_testbench_test
